import React, { useState, useMemo } from 'react';
import { Button } from '../common/Button';
import { CodeBlock } from '../common/CodeBlock';
import { SurfaceType } from '../../types';
import {
  BookOpen,
  Terminal,
  HardDrive,
  Server,
  Key,
  Code2,
  Search,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  HelpCircle,
  RefreshCw,
  Copy,
  Check,
  ShieldAlert,
  Sliders,
  ExternalLink,
} from 'lucide-react';

interface DocsInterfaceProps {
  onNavigateSurface: (surface: SurfaceType, path?: string) => void;
}

type SectionKey = 'getting-started' | 'storage' | 'hosting' | 'api' | 'cli' | 'errors' | 'sdk';

interface ErrorEntry {
  code: string;
  httpStatus: number;
  title: string;
  cause: string;
  solution: string;
  category: 'auth' | 'storage' | 'hosting' | 'rate-limit' | 'system';
}

export const DocsInterface: React.FC<DocsInterfaceProps> = ({ onNavigateSurface }) => {
  const [activeSection, setActiveSection] = useState<SectionKey>('getting-started');
  const [searchQuery, setSearchQuery] = useState('');
  const [errorSearch, setErrorSearch] = useState('');
  const [errorFilter, setErrorFilter] = useState<string>('all');
  const [copiedSnippet, setCopiedSnippet] = useState<string | null>(null);

  const sections = [
    { id: 'getting-started', label: 'Getting Started', icon: BookOpen, badge: 'Quickstart' },
    { id: 'storage', label: 'Cloud Storage API', icon: HardDrive },
    { id: 'hosting', label: 'Hosting & Deployments', icon: Server },
    { id: 'sdk', label: 'TypeScript SDK', icon: Code2 },
    { id: 'api', label: 'REST API Reference', icon: Key },
    { id: 'cli', label: 'Optic CLI Tooling', icon: Terminal },
    { id: 'errors', label: 'Error Handling & Codes', icon: ShieldAlert, badge: 'Updated' },
  ];

  const errorCatalog: ErrorEntry[] = [
    {
      code: 'ERR_AUTH_INVALID_KEY',
      httpStatus: 401,
      title: 'Invalid or Malformed API Key',
      cause: 'The bearer token provided in the Authorization header was not recognized, is expired, or was revoked in your Dashboard.',
      solution: 'Generate a new API key from Dashboard > API Keys. Ensure the header matches "Authorization: Bearer opt_live_...".',
      category: 'auth',
    },
    {
      code: 'ERR_AUTH_MISSING_CREDENTIALS',
      httpStatus: 401,
      title: 'Missing Authentication Header',
      cause: 'No Authorization header or API token was present in the incoming HTTP request.',
      solution: 'Include the header `Authorization: Bearer <your_key>` or set the `OPTIC_API_KEY` environment variable in your CLI/CI pipeline.',
      category: 'auth',
    },
    {
      code: 'ERR_STORAGE_QUOTA_EXCEEDED',
      httpStatus: 403,
      title: 'Storage Capacity Limit Reached',
      cause: 'Your developer account has reached the maximum 10 GB storage allotment on the current tier.',
      solution: 'Delete unused assets using the dashboard/CLI, or upgrade your plan from Dashboard > Settings.',
      category: 'storage',
    },
    {
      code: 'ERR_PAYLOAD_TOO_LARGE',
      httpStatus: 413,
      title: 'Direct Upload Size Exceeded',
      cause: 'Attempted a direct synchronous multipart upload exceeding the 100 MB single-request boundary.',
      solution: 'For large assets (>100 MB up to 5 GB), use presigned multipart chunked uploads via `optic.storage.createMultipartUpload()`.',
      category: 'storage',
    },
    {
      code: 'ERR_MIME_UNSUPPORTED',
      httpStatus: 415,
      title: 'Restricted File Type or Unrecognized MIME',
      cause: 'The uploaded file extension or magic byte header corresponds to an executable (.exe, .bat) banned by the Acceptable Use Policy.',
      solution: 'Review Optic AUP in Terms of Service. If uploading binary data, specify `mimeType: "application/octet-stream"` explicitly.',
      category: 'storage',
    },
    {
      code: 'ERR_BUILD_FAILED',
      httpStatus: 422,
      title: 'Hosting Build Command Failed',
      cause: 'The automated deployment container encountered a non-zero exit code during `npm run build` or `vite build`.',
      solution: 'Check the real-time build logs in Optic Hosting. Verify that all npm dependencies are declared in package.json and TypeScript compiles cleanly.',
      category: 'hosting',
    },
    {
      code: 'ERR_MISSING_DIST_DIRECTORY',
      httpStatus: 422,
      title: 'Output Directory Not Found',
      cause: 'The specified build artifact directory (e.g. `dist`, `build`, or `out`) was not generated by your build script.',
      solution: 'Ensure your framework build command outputs to the directory specified in your project configuration (default: `./dist`).',
      category: 'hosting',
    },
    {
      code: 'ERR_DOMAIN_CNAME_MISCONFIGURED',
      httpStatus: 400,
      title: 'DNS CNAME Verification Pending',
      cause: 'The DNS CNAME record for your custom domain has not propagated or does not point to `cname.optic.doy.best`.',
      solution: 'Add a CNAME record with Host "@" or subdomain pointing to "cname.optic.doy.best". DNS propagation may take 5 to 30 minutes.',
      category: 'hosting',
    },
    {
      code: 'ERR_RATE_LIMITED',
      httpStatus: 429,
      title: 'API Rate Limit Exceeded',
      cause: 'Exceeded the concurrent requests threshold (1,200 requests/minute per developer key).',
      solution: 'Implement exponential backoff. Inspect the `Retry-After` HTTP response header for wait duration in seconds.',
      category: 'rate-limit',
    },
    {
      code: 'ERR_PROJECT_NOT_FOUND',
      httpStatus: 404,
      title: 'Target Project ID Nonexistent',
      cause: 'The `projectId` or project name specified in the CLI or API call does not exist under your authenticated account.',
      solution: 'Run `npx optic projects list` or check the Hosting dashboard to verify the exact project identifier.',
      category: 'hosting',
    },
    {
      code: 'ERR_INTERNAL_EDGE_TIMEOUT',
      httpStatus: 504,
      title: 'Edge Worker Gateway Timeout',
      cause: 'The origin fetch or downstream object store did not respond within the 15-second execution deadline.',
      solution: 'Optic monitors edge health automatically. Retry the request with jitter; if persistent, verify your network connectivity.',
      category: 'system',
    },
  ];

  const filteredErrors = useMemo(() => {
    return errorCatalog.filter((err) => {
      const matchesSearch =
        err.code.toLowerCase().includes(errorSearch.toLowerCase()) ||
        err.title.toLowerCase().includes(errorSearch.toLowerCase()) ||
        err.cause.toLowerCase().includes(errorSearch.toLowerCase()) ||
        err.solution.toLowerCase().includes(errorSearch.toLowerCase());

      const matchesFilter = errorFilter === 'all' || err.category === errorFilter;
      return matchesSearch && matchesFilter;
    });
  }, [errorCatalog, errorSearch, errorFilter]);

  const copyCode = (code: string, id: string) => {
    navigator.clipboard.writeText(code);
    setCopiedSnippet(id);
    setTimeout(() => setCopiedSnippet(null), 2000);
  };

  return (
    <div className="w-full flex flex-col md:flex-row gap-6">
      {/* Sidebar */}
      <aside className="w-full md:w-56 border-b md:border-b-0 md:border-r border-zinc-800/80 pb-4 md:pb-0 md:pr-4 space-y-3 shrink-0">
          <div className="text-[11px] font-mono uppercase tracking-wider text-zinc-500 font-semibold px-2 mb-2">
            Documentation
          </div>

          <div className="space-y-1">
            {sections.map((sec) => {
              const Icon = sec.icon;
              const isActive = activeSection === sec.id;
              return (
                <button
                  key={sec.id}
                  onClick={() => setActiveSection(sec.id as SectionKey)}
                  className={`w-full flex items-center justify-between px-3 py-2 rounded-lg text-xs font-medium transition-colors ${
                    isActive
                      ? 'bg-zinc-800 text-white font-semibold'
                      : 'text-zinc-400 hover:text-zinc-100 hover:bg-zinc-900'
                  }`}
                >
                  <div className="flex items-center gap-2.5">
                    <Icon size={15} className={isActive ? 'text-sky-400' : 'text-zinc-400'} />
                    <span>{sec.label}</span>
                  </div>
                  {sec.badge && (
                    <span
                      className={`text-[9px] font-mono px-1.5 py-0.5 rounded font-medium ${
                        sec.id === 'errors'
                          ? 'bg-amber-950/80 text-amber-300 border border-amber-800/60'
                          : 'bg-zinc-800 text-zinc-400'
                      }`}
                    >
                      {sec.badge}
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {/* Quick Support / Legal Links in sidebar */}
          <div className="pt-4 border-t border-zinc-800/80 space-y-1">
            <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-500 font-semibold px-2 block mb-1">
              Resources
            </span>
            <button
              onClick={() => onNavigateSurface('privacy', '/privacy')}
              className="w-full text-left px-3 py-1.5 rounded-md text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
            >
              Privacy Policy
            </button>
            <button
              onClick={() => onNavigateSurface('terms', '/terms')}
              className="w-full text-left px-3 py-1.5 rounded-md text-xs text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
            >
              Terms of Service
            </button>
          </div>
        </aside>

        {/* Content */}
        <main className="flex-1 p-6 lg:p-10 max-w-4xl space-y-10 overflow-y-auto">
          {/* Mobile section picker */}
          <div className="md:hidden flex flex-wrap gap-1.5 pb-4 border-b border-zinc-800">
            {sections.map((sec) => (
              <button
                key={sec.id}
                onClick={() => setActiveSection(sec.id as SectionKey)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${
                  activeSection === sec.id
                    ? 'bg-zinc-800 text-white font-semibold'
                    : 'text-zinc-400 bg-zinc-900/60'
                }`}
              >
                {sec.label}
              </button>
            ))}
          </div>

          {/* Section: Getting Started */}
          {activeSection === 'getting-started' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">Getting Started with Optic</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  Optic unifies high-performance cloud object storage and edge web hosting into a
                  single developer workspace with instant CLI and SDK integration.
                </p>
              </div>

              <div className="p-4 rounded-xl bg-zinc-900/40 border border-zinc-800/80 space-y-2 text-xs">
                <span className="font-mono text-sky-400 font-semibold uppercase tracking-wider block">
                  Key Specifications
                </span>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 pt-1 text-zinc-300">
                  <div>
                    <span className="text-zinc-500 block">Object Storage:</span>
                    <strong className="text-zinc-200">Cloudflare R2 / S3 API</strong>
                  </div>
                  <div>
                    <span className="text-zinc-500 block">Edge Network:</span>
                    <strong className="text-zinc-200">Global Anycast CDN</strong>
                  </div>
                  <div>
                    <span className="text-zinc-500 block">SSL Certificates:</span>
                    <strong className="text-zinc-200">Automated Let&apos;s Encrypt</strong>
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">1. Install the Optic CLI</h2>
                <p className="text-xs text-zinc-400">
                  Deploy sites and sync assets directly from your continuous integration pipeline or local terminal.
                </p>
                <CodeBlock
                  language="bash"
                  code={`# Run directly via npx without global installation
npx optic --help

# Or install globally
npm install -g @optic/cli`}
                />
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">2. Authenticate CLI</h2>
                <p className="text-xs text-zinc-400">
                  Generate a secret token in your Optic Dashboard under <strong className="text-zinc-200">API Keys</strong>.
                </p>
                <CodeBlock
                  language="bash"
                  code={`export OPTIC_API_KEY="opt_live_your_secret_key"
npx optic auth check`}
                />
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">3. Deploy your first site</h2>
                <CodeBlock
                  language="bash"
                  code={`cd my-static-project
npx optic deploy ./dist --project my-portfolio`}
                />
              </div>
            </div>
          )}

          {/* Section: Cloud Storage */}
          {activeSection === 'storage' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">Cloud Storage API</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  Upload, stream, and manage assets globally with S3-compatible endpoints backed by
                  Cloudflare R2 object storage with zero egress fees.
                </p>
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">Upload Asset via TypeScript SDK</h2>
                <CodeBlock
                  language="typescript"
                  code={`import { OpticClient } from '@optic/sdk';
import fs from 'node:fs';

const optic = new OpticClient({
  apiKey: process.env.OPTIC_API_KEY!,
});

async function uploadFile() {
  const fileStream = fs.createReadStream('./assets/bundle.tar.gz');

  const upload = await optic.storage.upload({
    filename: 'bundle.tar.gz',
    body: fileStream,
    isPublic: true,
    contentType: 'application/gzip',
  });

  console.log('Public CDN URL:', upload.url);
  // Output: https://cdn.optic.doy.best/uploads/bundle.tar.gz
}`}
                />
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">Generate Presigned Download Link</h2>
                <p className="text-xs text-zinc-400">
                  Provide temporary, expiring URLs for private files without exposing your master API credentials.
                </p>
                <CodeBlock
                  language="typescript"
                  code={`const presigned = await optic.storage.createPresignedUrl({
  fileId: 'file_9a8b7c',
  expiresInSeconds: 3600, // 1 hour
});

console.log('Expiring Download Link:', presigned.downloadUrl);`}
                />
              </div>
            </div>
          )}

          {/* Section: Hosting */}
          {activeSection === 'hosting' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">Hosting &amp; Deployments</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  Optic Hosting provides edge routing with zero cold-starts, automatic SSL, and atomic deployments.
                </p>
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">Custom Domain DNS Configuration</h2>
                <p className="text-xs text-zinc-400">
                  To point your domain or subdomain to an Optic project, create a DNS CNAME record at your DNS provider (Cloudflare, Namecheap, Route 53):
                </p>
                <div className="p-3.5 rounded-lg bg-zinc-950 border border-zinc-800 font-mono text-xs text-zinc-200 space-y-1">
                  <div>Type: <span className="text-sky-400 font-bold">CNAME</span></div>
                  <div>Host / Name: <span className="text-zinc-400">app (or @ for root via ALIAS/Flattening)</span></div>
                  <div>Target / Value: <span className="text-emerald-400 font-bold">cname.optic.doy.best</span></div>
                  <div>TTL: <span className="text-zinc-500">Automatic / 300 seconds</span></div>
                </div>
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">Single Page Application (SPA) Routing</h2>
                <p className="text-xs text-zinc-400">
                  Include an <code className="text-zinc-200 font-mono">optic.json</code> configuration in your project root to handle client-side routing rewrites:
                </p>
                <CodeBlock
                  language="json"
                  code={`{
  "version": 1,
  "routes": [
    { "src": "/api/(.*)", "dest": "/api/$1" },
    { "handle": "filesystem" },
    { "src": "/(.*)", "dest": "/index.html" }
  ]
}`}
                />
              </div>
            </div>
          )}

          {/* Section: TypeScript SDK */}
          {activeSection === 'sdk' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">Optic TypeScript SDK</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  The official isomorphic Node.js and Browser SDK provides end-to-end type safety for storage, deployments, and authentication.
                </p>
              </div>

              <CodeBlock
                language="bash"
                code={`npm install @optic/sdk`}
              />

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">Client Initialization &amp; Usage</h2>
                <CodeBlock
                  language="typescript"
                  code={`import { OpticClient } from '@optic/sdk';

export const optic = new OpticClient({
  apiKey: process.env.OPTIC_API_KEY,
  endpoint: 'https://api.optic.doy.best/v1',
  timeoutMs: 15000,
});

// List files with pagination
const { files, total } = await optic.storage.listFiles({
  limit: 20,
  prefix: 'builds/',
});

// Trigger atomic deployment
const deployment = await optic.hosting.deploy({
  projectId: 'proj_ecommerce',
  commitHash: '7c9e01a',
  branch: 'main',
});`}
                />
              </div>
            </div>
          )}

          {/* Section: REST API Reference */}
          {activeSection === 'api' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">REST API Reference</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  Every operation in the web console can be executed programmatically via our HTTPS API.
                </p>
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">1. Verify Authentication Token</h2>
                <CodeBlock
                  language="bash"
                  code={`curl https://api.optic.doy.best/v1/auth/verify \\
  -H "Authorization: Bearer opt_live_9a7b4f2c..."`}
                />
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">2. List Storage Objects</h2>
                <CodeBlock
                  language="bash"
                  code={`curl -X GET "https://api.optic.doy.best/v1/storage/files?limit=25" \\
  -H "Authorization: Bearer opt_live_9a7b4f2c..."`}
                />
              </div>

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">3. Trigger Instant Deployment</h2>
                <CodeBlock
                  language="bash"
                  code={`curl -X POST https://api.optic.doy.best/v1/deployments \\
  -H "Authorization: Bearer opt_live_9a7b4f2c..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "projectId": "proj_my_portfolio",
    "branch": "main",
    "commitMessage": "Release v2.4.0"
  }'`}
                />
              </div>
            </div>
          )}

          {/* Section: Optic CLI Tooling */}
          {activeSection === 'cli' && (
            <div className="space-y-6">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-white">Optic CLI Tooling</h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  A lightweight terminal companion for your local development workflow and continuous integration.
                </p>
              </div>

              <CodeBlock
                language="bash"
                code={`# Global command overview
npx optic --help

Commands:
  optic login       Authenticate with your Optic developer account
  optic deploy      Deploy current directory or build folder to Optic Hosting
  optic storage     List, sync, or upload files directly to Optic Cloud
  optic projects    Manage and inspect hosting project bindings
  optic whoami      Display active account and API key identifier`}
              />

              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">GitHub Actions CI/CD Workflow</h2>
                <p className="text-xs text-zinc-400">
                  Deploy automatically on every push to <code className="text-zinc-200 font-mono">main</code>:
                </p>
                <CodeBlock
                  language="yaml"
                  code={`name: Optic Continuous Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Deploy to Optic Hosting
        run: npx optic deploy ./dist --project my-app
        env:
          OPTIC_API_KEY: \${{ secrets.OPTIC_API_KEY }}`}
                />
              </div>
            </div>
          )}

          {/* Section: Error Handling & Troubleshooting (COMPREHENSIVE) */}
          {activeSection === 'errors' && (
            <div className="space-y-8">
              <div>
                <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-amber-950/50 border border-amber-800/50 text-[11px] font-mono text-amber-400 mb-2">
                  <ShieldAlert size={12} />
                  <span>Developer Resilience Guide</span>
                </div>
                <h1 className="text-2xl font-bold tracking-tight text-white">
                  Error Handling, Status Codes &amp; Troubleshooting
                </h1>
                <p className="text-sm text-zinc-400 mt-2 leading-relaxed">
                  All Optic APIs and CLI outputs return consistent, machine-readable JSON error
                  structures with deterministic HTTP status codes and remediation links.
                </p>
              </div>

              {/* Standard Error Response Schema */}
              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">
                  1. Standard JSON Error Schema
                </h2>
                <p className="text-xs text-zinc-400">
                  When an API request fails, the response payload adheres to the RFC 7807 Problem
                  Details specification:
                </p>
                <CodeBlock
                  language="json"
                  code={`{
  "error": {
    "code": "ERR_AUTH_INVALID_KEY",
    "status": 401,
    "message": "The provided API key has been revoked or expired.",
    "doc_url": "https://docs.optic.doy.best/errors#ERR_AUTH_INVALID_KEY",
    "request_id": "req_8f19da2e0b5c"
  }
}`}
                />
              </div>

              {/* Robust TypeScript Error Handling Pattern */}
              <div className="space-y-3">
                <h2 className="text-base font-semibold text-zinc-200">
                  2. Production Error Handling Pattern with Exponential Backoff
                </h2>
                <p className="text-xs text-zinc-400">
                  Use this recommended try/catch structure with automatic retry for rate limits
                  (429) and transient network disconnects:
                </p>
                <CodeBlock
                  language="typescript"
                  code={`import { OpticClient, OpticApiError, OpticRateLimitError } from '@optic/sdk';

const optic = new OpticClient({ apiKey: process.env.OPTIC_API_KEY! });

async function resilientDeploy(retries = 3): Promise<void> {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const result = await optic.hosting.deploy({ projectId: 'my-app' });
      console.log('Deployed successfully:', result.url);
      return;
    } catch (err: unknown) {
      if (err instanceof OpticRateLimitError) {
        // Obey Retry-After header
        const waitMs = (err.retryAfterSeconds || Math.pow(2, attempt)) * 1000;
        console.warn(\`Rate limited. Retrying in \${waitMs}ms...\`);
        await new Promise((resolve) => setTimeout(resolve, waitMs));
        continue;
      }

      if (err instanceof OpticApiError) {
        console.error(\`API Error [\${err.code}]: \${err.message}\`);
        console.error(\`Documentation: \${err.docUrl}\`);
        // Fatal client error (e.g. 401 Auth, 403 Quota) - do not retry
        throw err;
      }

      // Transient Network Error
      if (attempt < retries) {
        const backoff = Math.pow(2, attempt) * 500;
        console.warn(\`Network glitch. Retrying attempt \${attempt + 1}...\`);
        await new Promise((resolve) => setTimeout(resolve, backoff));
      } else {
        throw err;
      }
    }
  }
}`}
                />
              </div>

              {/* Interactive Error Catalog Filter & Search */}
              <div className="space-y-4 pt-4 border-t border-zinc-800">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold text-zinc-200">
                      3. Error Code Catalog &amp; Solutions
                    </h2>
                    <p className="text-xs text-zinc-400">
                      Search error codes or filter by infrastructure subsystem.
                    </p>
                  </div>

                  {/* Filter Pills */}
                  <div className="flex items-center gap-1 overflow-x-auto text-[11px] font-mono">
                    {['all', 'auth', 'storage', 'hosting', 'rate-limit'].map((cat) => (
                      <button
                        key={cat}
                        onClick={() => setErrorFilter(cat)}
                        className={`px-2.5 py-1 rounded-md capitalize transition-colors ${
                          errorFilter === cat
                            ? 'bg-zinc-800 text-sky-400 font-semibold border border-zinc-700'
                            : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-900'
                        }`}
                      >
                        {cat}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Search Bar */}
                <div className="relative">
                  <Search size={14} className="absolute left-3 top-3 text-zinc-500" />
                  <input
                    type="text"
                    placeholder="Search error code (e.g. ERR_AUTH_INVALID_KEY, 429, quota, CNAME)..."
                    value={errorSearch}
                    onChange={(e) => setErrorSearch(e.target.value)}
                    className="w-full pl-9 pr-4 py-2 rounded-lg bg-zinc-900/60 border border-zinc-800 text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-zinc-700 font-mono"
                  />
                </div>

                {/* Errors List */}
                <div className="space-y-3">
                  {filteredErrors.length === 0 ? (
                    <div className="p-8 text-center border border-zinc-800 rounded-xl bg-zinc-900/20 text-xs text-zinc-500 font-mono">
                      No error codes match &quot;{errorSearch}&quot;.
                    </div>
                  ) : (
                    filteredErrors.map((err) => (
                      <div
                        key={err.code}
                        id={err.code}
                        className="p-4 rounded-xl bg-zinc-900/40 border border-zinc-800/80 space-y-2.5"
                      >
                        <div className="flex flex-wrap items-center justify-between gap-2">
                          <div className="flex items-center gap-2">
                            <span className="px-2 py-0.5 rounded bg-zinc-950 border border-zinc-800 font-mono text-xs font-bold text-sky-400">
                              {err.code}
                            </span>
                            <span
                              className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${
                                err.httpStatus >= 500
                                  ? 'bg-red-950/60 text-red-400 border border-red-900/40'
                                  : err.httpStatus === 429
                                  ? 'bg-amber-950/60 text-amber-400 border border-amber-900/40'
                                  : 'bg-zinc-800 text-zinc-400'
                              }`}
                            >
                              HTTP {err.httpStatus}
                            </span>
                          </div>
                          <span className="text-[10px] font-mono uppercase tracking-wider text-zinc-500">
                            {err.category}
                          </span>
                        </div>

                        <div className="text-xs font-semibold text-zinc-200">{err.title}</div>

                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs pt-1">
                          <div className="p-2.5 rounded-lg bg-zinc-950/70 border border-zinc-800/60 space-y-1">
                            <div className="text-[11px] font-mono text-zinc-400 flex items-center gap-1.5">
                              <AlertTriangle size={12} className="text-amber-400 shrink-0" />
                              <span>Likely Root Cause</span>
                            </div>
                            <p className="text-zinc-400 leading-relaxed">{err.cause}</p>
                          </div>

                          <div className="p-2.5 rounded-lg bg-emerald-950/20 border border-emerald-900/30 space-y-1">
                            <div className="text-[11px] font-mono text-emerald-400 flex items-center gap-1.5">
                              <CheckCircle2 size={12} className="text-emerald-400 shrink-0" />
                              <span>Remediation Step</span>
                            </div>
                            <p className="text-zinc-300 leading-relaxed">{err.solution}</p>
                          </div>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          )}
        </main>
    </div>
  );
};
